name: simple_store
description: A flutter Single Data Flow framework that manages app state and navigation.
version: 0.1.0
homepage: https://github.com/jacokoo/simple-store

environment:
    sdk: ">=2.7.0 <3.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter
    simple_store_base: ^0.1.0

dev_dependencies:
    pedantic: ^1.11.0

flutter:
