name: simple_store_gen
description: Code generators for simple_store
version: 0.1.0
homepage: https://github.com/jacokoo/simple-store

environment:
    sdk: '>=2.8.1 <3.0.0'

dependencies:
    source_gen: ^0.9.10+1
    analyzer: ^0.41.2
    build: ^1.6.1
    build_config: ^0.4.5
    simple_store_base: ^0.1.0

dev_dependencies:
    pedantic: ^1.9.0
    test: ^1.14.4
