name: simple_store_base
description: Define common classes for simple_store and simple_store_gen.
version: 0.1.0
homepage: https://github.com/jacokoo/simple-store

environment:
    sdk: '>=2.8.1 <3.0.0'

dependencies:
    meta: ^1.2.4

dev_dependencies:
    pedantic: ^1.9.0
    test: ^1.14.4
